@echo off
set env_mode=%1
set env_value=%2
if "%1" == "" (
    set env_mode="--name"
    set env_value="turb"
)
echo [TURBNNGEN] Creating conda environment %env_mode% %env_value% ...
CALL conda create %env_mode% %env_value% python=3.11 --yes
echo [TURBNNGEN] Activating conda environnement %env_value% ...
CALL conda activate %env_value%
echo [TURBNNGEN] Installing pytorch ...
CALL conda install pytorch torchvision torchaudio pytorch-cuda=11.8 -c pytorch -c nvidia --yes
echo [TURBNNGEN] Installing conda requirements ...
CALL conda install --file conda_requirements --yes
echo [TURBNNGEN] Installing pip requirements ...
CALL pip install -r pip_requirements.txt
echo [TURBNNGEN] Installing source code ...
call python -m pip install -e .