DATAPATH = "/users/local/f22dimar/TurbNNGen/data/MRW.npz"
SCALERPATH = "/users/local/f22dimar/TurbNNGen/data/scaler.joblib"
DATAPATH_fm_desktop = "C:/Users/fiona/anaconda3/envs/TurbNNGen/TurbNNGen_git/data/MRW.npz"
SCALERPATH_fm_desktop = "C:/Users/fiona/anaconda3/envs/TurbNNGen/TurbNNGen_git/data/scaler.joblib"
DATAPATH_fm = "/homes/f21marti/Documents/TurbNNGen/data/MRW.npz"
SCALERPATH_fm = "/homes/f21marti/Documents/TurbNNGen/data/scaler.joblib"